config/routes.rb
DevSurvey::Application.routes.draw do

  root to: "main#index"
  get '/thanks', to: 'main#thanks'

  ### Users

  resources :users do
    resources :surveys, only: [:show]
  end

  resources :surveys, only: [:new, :create]

  namespace :admin do
    resources :surveys, only: [:index, :show, :destroy]
    resources :questions, except: [:destroy] do
      member do
        post :archive
      end
    end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  after_save :send_survey_completed, :only => :create

  belongs_to :user
  has_many :answers,:dependent => :destroy
  has_many :questions, :through => :answers

  accepts_nested_attributes_for :answers

  validates :user, :presence => true
  validate :required_questions_completed

  def answers_by_question
    answers.includes(:question).group_by(&:question)  
  end

  private

  def required_questions_completed
    if user_id
      @required_questions = user.dev? ? required_dev_questions : required_company_questions
      if @required_questions.count != answers_for_required_questions.count
        errors.add(:user_id, "Please answer all required questions")
      end
    end
  end

  def required_dev_questions
    Question.required_for_dev
  end

  def required_company_questions
    Question.required_for_company
  end

  def answers_for_required_questions
    answers.select do |answer|
      answer.question.present? && answer.question.required?
    end
  end

  def send_survey_completed
    AdminMailer.notify_admin(self.id).deliver_later
  end

end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController <ApplicationController
  before_action :validate_rights, :only => [:index, :show, :destroy]

  def index
    @surveys = Survey.paginate(:page => params[:page])
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def destroy
    @survey = Survey.destroy(params[:id])
    redirect_to admin_surveys_path
  end

  private

  def validate_rights
    redirect_to root_path unless params[:token] && params[:token] == ENV['ADMIN_SECRET_KEY']
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :validate_rights, :only => [:new]

  def new
    @user = User.where(:token => params[:token]).first
    redirect_to root_path(@user, @user.survey.id) if @user.survey_completed?
    @survey = @user.build_survey
    setup_questions
    @questions.each { @survey.answers.build }
  end

  def create
    @user = User.find(params[:survey][:user_id])
    @survey = @user.build_survey(survey_params)
    if @survey.save
      redirect_to thanks_path
    else
      setup_questions
      flash[:error] = 'Please amend the errors indicated below.'
      render :new
    end
  end

  def setup_questions
     @user.dev? ? setup_dev_questions : setup_company_questions
  end

  private

  def survey_params
    params.require(:survey).permit(
      :answers_attributes => [:id, :question_id, :text, 
      :question_answer_choices_attributes => [:possible_answer_id]]
    )
  end

  def setup_dev_questions
    @questions = (Question.for_dev + Question.general).sort_by do |q|
      q.question_group
    end
  end

  def setup_company_questions
    @questions = (Question.for_company + Question.general).sort_by do |q|
      q.question_group
    end
  end

  def validate_rights
    redirect_to root_path if !params[:token]
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
  def show_explanation_for(question)
    html = "<p class='explain'>#{question.explanation}</p>"
    html.html_safe
  end

  def admin_time_string(time)
    format = '%a, %d %b <em class="meta">%H:%M UTC</em>'
    time.strftime(format)
  end

  def answers_for_radio_select(answers)
    if answers.first.question_answer_choices.any?
      answers.first.question_answer_choices.first.possible_answer.text
    end
  end

  def answers_for_checkbox(answers)
    html = "<ul class='profile_answers'>"
      answers.first.question_answer_choices.each do |sa|
        html << content_tag(:li, sa.possible_answer.text)
      end
      html << "</ul>"
      html.html_safe
  end

  def answers_for_textarea(answers)
    answers.first.text
  end
end

app/views/admin/surveys/_questions.html.erb
<% if @survey.questions.any? %>
  <% @survey.answers_by_question.each do |question, answers| %>
    <h4><%= question.title %></h4>
    <% if answers.any? %>
     
      <% case question.field_type %>
      <% when "RadioSelect" %>
        <%= answers_for_radio_select answers %>
      <% when "Textarea" %>
        <%= answers_for_textarea answers %>
      <% when "Checkbox" %>
        <%= answers_for_checkbox answers %>
      <% else %>
        <p><%= answers.first.text %></p>
      <% end %>
      
    <% else %>
      <p>n/a</p>
    <% end %>
  <% end %>
<% end %>

app/views/admin/surveys/index.html.erb
<% content_for :body_class, 'admin-surveys index' %>
<% content_for :body_id,    'admin-surveys-index' %>
<% content_for :page_title, 'Surveys' %>

<% if @surveys.any? %>
<div class="table-section">
  <table cellspacing="0" class="stripe">
    <thead>
      <tr>
        <th>Id</th>
        <th>Created at</th>
        <th>Submitted by</th>
      </tr>
    </thead>

    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <td>
            <span title="<%= survey.id %>">
              <%= survey.id %>
            </span>
          </td>
          <td>
            <span title="<%= time_ago_in_words(survey.created_at).html_safe %> ago">
              <%= admin_time_string(survey.created_at).html_safe %>
            </span>
          </td>
          <td><%= survey.user.email %></td>
          <td class="controls ">
            <%= link_to 'details', admin_survey_path(survey), :class=> 'btn' %>
          </td>
        </tr>
      <% end %> <%# @surveys.each %>
    </tbody>
  </table>
</div>

<%= will_paginate @surveys %>

<% else %>
<div class="empty">
  There are no surveys available.
</div>
<% end %>

app/views/admin/surveys/show.html.erb
<% content_for :body_class, 'admin-surveys show' %>
<% content_for :body_id,    'admin-surveys-show' %>
<% content_for :page_title, 'Surveys' %>

<% content_for :page_header do %>
  <h2>
    <%= link_to yield(:page_title), admin_surveys_path %> &gt;
    <%=h @survey.id %>
  </h2>

<% end %>

<div id="admin-content">
  <dl>
    <dt>Submitter</dt>
    <dd><%= @survey.user.email %></dd>
    <dt>Questions</dt>
    <dd><%= render 'questions' %></dd>
  </dl>

</div>