config/routes.rb
DevSurvey::Application.routes.draw do

  root to: "main#index"
  get '/thanks', to: 'main#thanks'

  ### Users

  resources :users do
    resources :surveys, only: [:show]
  end

  resources :surveys, only: [:new, :create]

  namespace :admin do
    resources :surveys, only: [:index, :show, :destroy]
    resources :questions, except: [:destroy] do
      member do
        post :archive
      end
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  QUESTION_TYPES = %w(TextField Checkbox RadioSelect Textarea)

  ## Associations
  has_many :answers
  has_many :possible_answers, :dependent => :destroy
  belongs_to :question_group

  ## Validations
  validates :question_group, :presence => true
  validates :title, :presence => true
  validates :position, :uniqueness => true, numericality: { only_integer: true }
  validates :field_type,
      :presence => true, :inclusion => { :in => QUESTION_TYPES }

  ## Class Methods ##
  def self.by_position
    order(position: :asc)
  end

  def self.for_dev
    joins(:question_group).merge(QuestionGroup.dev).by_position
  end

  def self.for_company
    joins(:question_group).merge(QuestionGroup.company).by_position
  end

  def self.general
    joins(:question_group).merge(QuestionGroup.general).by_position
  end

  def self.required_for_dev
    (required.for_dev + required.general)
  end

  def self.required_for_company
    (required.for_company + required.general)
  end

  ## Scopes ##
  scope :required, -> { where(:required => true ) }
  scope :required_general, -> { required.general }

  def answers_by_possible_answer
    Hash[possible_answers.map {|pa| [pa, pa.answers.count]}]
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController <ApplicationController
  before_action :validate_rights
  before_action :setup_question, only: [:show, :edit, :update, :archive]

  def index
    @questions = Question.paginate(:page => params[:page])
  end

  def show    
  end
  
  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to admin_questions_path
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @question.update(question_params)
      redirect_to admin_questions_path
    else
      render :edit
    end
  end
  
  def archive
    @question = Question.find(params[:id])
  end

  private
  def question_params
    params.require(:question).permit(:title, :explanation, :field_type, :question_group_id,
     :required, :position)
  end

  def validate_rights
    redirect_to root_path unless params[:token] && params[:token] == ENV['ADMIN_SECRET_KEY']
  end

  def setup_question
    @question = Question.find(params[:id])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_groups_dropdown(form)
    form.select(
      :question_group_id,
      QuestionGroup.all.map { |qg| [qg.name, qg.id] },
      { prompt: 'Select one' }
    )
  end

end

app/views/admin/questions/_fields.html.haml
%fieldset
  = fields_for @question do |f|
    %ul
      %li
        = f.label :question_group
        = question_groups_dropdown(f)
      %li
        = f.label :title
        = f.text_field :title
      
      %li
        = f.label :explanation
        = f.text_field :explanation
      
      %li
        = f.label :field_type
        = f.select(:field_type, Question::QUESTION_TYPES.map { |type| [type.underscore.humanize, type.to_s]}, { prompt: 'Select one' })
      
      %li.inverse
        = f.check_box :required
        = f.label :required
        
      %li
        = f.label :position
        = f.text_field :position
      

app/views/admin/questions/create.html.haml
create.html.haml

app/views/admin/questions/edit.html.haml
= render partial: 'form', locals: {question: @question}

app/views/admin/questions/index.html.haml
%table
  %thead
    %tr
      %td Position
      %td Title
      %td Number of Answers

  - @questions.each do |question|
    %tr
      %td= question.position
      %td= question.title 
      %td= question.answers.count
      %td= link_to 'View', admin_question_path(question)
      %td= link_to 'Edit', edit_admin_question_path(question)
      %td= link_to 'Delete', archive_admin_question_path(question)

app/views/admin/questions/new.html.haml
- content_for :page_title, "Add new question" 

%h2= yield :page_title 
= object_title(@question_group) if @question_group 

= error_messages_for @question 
= form_for [:admin, @question], as: :question, html: { class: "standard" },
  url: admin_questions_path do |f| 
  = render :partial => 'fields', :locals => { :f => f } 
  = f.button 'Save', class: 'btn btn-success'

app/views/admin/questions/show.html.haml
%section.price
  %h3= @question.title
  - if @question.answers.any?
    %table
      - @question.answers_by_possible_answer.each do |pa,count|
        %tr
          %td= pa.text
          %td= count